export interface CountryEntry {
    code: string;
    name: string;
    dialCode: string;
    flag: string;
}

export const COUNTRIES: CountryEntry[] = [
    // Russia first (default)
    { code: "RU", name: "Россия", dialCode: "+7", flag: "🇷🇺" },
    // Rest in Russian alphabetical order
    { code: "AU", name: "Австралия", dialCode: "+61", flag: "🇦🇺" },
    { code: "AT", name: "Австрия", dialCode: "+43", flag: "🇦🇹" },
    { code: "AZ", name: "Азербайджан", dialCode: "+994", flag: "🇦🇿" },
    { code: "AL", name: "Албания", dialCode: "+355", flag: "🇦🇱" },
    { code: "DZ", name: "Алжир", dialCode: "+213", flag: "🇩🇿" },
    { code: "VI", name: "Американские Виргинские о-ва", dialCode: "+1340", flag: "🇻🇮" },
    { code: "AS", name: "Американское Самоа", dialCode: "+1684", flag: "🇦🇸" },
    { code: "AI", name: "Ангилья", dialCode: "+1264", flag: "🇦🇮" },
    { code: "AO", name: "Ангола", dialCode: "+244", flag: "🇦🇴" },
    { code: "AD", name: "Андорра", dialCode: "+376", flag: "🇦🇩" },
    { code: "AG", name: "Антигуа и Барбуда", dialCode: "+1268", flag: "🇦🇬" },
    { code: "AR", name: "Аргентина", dialCode: "+54", flag: "🇦🇷" },
    { code: "AM", name: "Армения", dialCode: "+374", flag: "🇦🇲" },
    { code: "AW", name: "Аруба", dialCode: "+297", flag: "🇦🇼" },
    { code: "AF", name: "Афганистан", dialCode: "+93", flag: "🇦🇫" },
    { code: "BS", name: "Багамы", dialCode: "+1242", flag: "🇧🇸" },
    { code: "BD", name: "Бангладеш", dialCode: "+880", flag: "🇧🇩" },
    { code: "BB", name: "Барбадос", dialCode: "+1246", flag: "🇧🇧" },
    { code: "BH", name: "Бахрейн", dialCode: "+973", flag: "🇧🇭" },
    { code: "BY", name: "Беларусь", dialCode: "+375", flag: "🇧🇾" },
    { code: "BZ", name: "Белиз", dialCode: "+501", flag: "🇧🇿" },
    { code: "BE", name: "Бельгия", dialCode: "+32", flag: "🇧🇪" },
    { code: "BJ", name: "Бенин", dialCode: "+229", flag: "🇧🇯" },
    { code: "BM", name: "Бермудские Острова", dialCode: "+1441", flag: "🇧🇲" },
    { code: "BG", name: "Болгария", dialCode: "+359", flag: "🇧🇬" },
    { code: "BO", name: "Боливия", dialCode: "+591", flag: "🇧🇴" },
    { code: "BQ", name: "Бонэйр, Синт-Эстатиус и Саба", dialCode: "+599", flag: "🇧🇶" },
    { code: "BA", name: "Босния и Герцеговина", dialCode: "+387", flag: "🇧🇦" },
    { code: "BW", name: "Ботсвана", dialCode: "+267", flag: "🇧🇼" },
    { code: "BR", name: "Бразилия", dialCode: "+55", flag: "🇧🇷" },
    { code: "VG", name: "Британские Виргинские о-ва", dialCode: "+1284", flag: "🇻🇬" },
    { code: "BN", name: "Бруней", dialCode: "+673", flag: "🇧🇳" },
    { code: "BF", name: "Буркина-Фасо", dialCode: "+226", flag: "🇧🇫" },
    { code: "BI", name: "Бурунди", dialCode: "+257", flag: "🇧🇮" },
    { code: "BT", name: "Бутан", dialCode: "+975", flag: "🇧🇹" },
    { code: "VU", name: "Вануату", dialCode: "+678", flag: "🇻🇺" },
    { code: "GB", name: "Великобритания", dialCode: "+44", flag: "🇬🇧" },
    { code: "HU", name: "Венгрия", dialCode: "+36", flag: "🇭🇺" },
    { code: "VE", name: "Венесуэла", dialCode: "+58", flag: "🇻🇪" },
    { code: "TL", name: "Восточный Тимор", dialCode: "+670", flag: "🇹🇱" },
    { code: "VN", name: "Вьетнам", dialCode: "+84", flag: "🇻🇳" },
    { code: "GA", name: "Габон", dialCode: "+241", flag: "🇬🇦" },
    { code: "HT", name: "Гаити", dialCode: "+509", flag: "🇭🇹" },
    { code: "GY", name: "Гайана", dialCode: "+592", flag: "🇬🇾" },
    { code: "GM", name: "Гамбия", dialCode: "+220", flag: "🇬🇲" },
    { code: "GH", name: "Гана", dialCode: "+233", flag: "🇬🇭" },
    { code: "GP", name: "Гваделупа", dialCode: "+590", flag: "🇬🇵" },
    { code: "GT", name: "Гватемала", dialCode: "+502", flag: "🇬🇹" },
    { code: "GF", name: "Гвиана", dialCode: "+594", flag: "🇬🇫" },
    { code: "GN", name: "Гвинея", dialCode: "+224", flag: "🇬🇳" },
    { code: "GW", name: "Гвинея-Бисау", dialCode: "+245", flag: "🇬🇼" },
    { code: "DE", name: "Германия", dialCode: "+49", flag: "🇩🇪" },
    { code: "GI", name: "Гибралтар", dialCode: "+350", flag: "🇬🇮" },
    { code: "HN", name: "Гондурас", dialCode: "+504", flag: "🇭🇳" },
    { code: "HK", name: "Гонконг", dialCode: "+852", flag: "🇭🇰" },
    { code: "GD", name: "Гренада", dialCode: "+1473", flag: "🇬🇩" },
    { code: "GL", name: "Гренландия", dialCode: "+299", flag: "🇬🇱" },
    { code: "GR", name: "Греция", dialCode: "+30", flag: "🇬🇷" },
    { code: "GE", name: "Грузия", dialCode: "+995", flag: "🇬🇪" },
    { code: "GU", name: "Гуам", dialCode: "+1671", flag: "🇬🇺" },
    { code: "DK", name: "Дания", dialCode: "+45", flag: "🇩🇰" },
    { code: "DJ", name: "Джибути", dialCode: "+253", flag: "🇩🇯" },
    { code: "IO", name: "Диего-Гарсия", dialCode: "+246", flag: "🇮🇴" },
    { code: "DM", name: "Доминика", dialCode: "+1767", flag: "🇩🇲" },
    { code: "DO", name: "Доминиканская Республика", dialCode: "+1809", flag: "🇩🇴" },
    { code: "DO", name: "Доминиканская Республика", dialCode: "+1829", flag: "🇩🇴" },
    { code: "DO", name: "Доминиканская Республика", dialCode: "+1849", flag: "🇩🇴" },
    { code: "EG", name: "Египет", dialCode: "+20", flag: "🇪🇬" },
    { code: "ZM", name: "Замбия", dialCode: "+260", flag: "🇿🇲" },
    { code: "ZW", name: "Зимбабве", dialCode: "+263", flag: "🇿🇼" },
    { code: "IL", name: "Израиль", dialCode: "+972", flag: "🇮🇱" },
    { code: "IN", name: "Индия", dialCode: "+91", flag: "🇮🇳" },
    { code: "ID", name: "Индонезия", dialCode: "+62", flag: "🇮🇩" },
    { code: "JO", name: "Иордания", dialCode: "+962", flag: "🇯🇴" },
    { code: "IQ", name: "Ирак", dialCode: "+964", flag: "🇮🇶" },
    { code: "IR", name: "Иран", dialCode: "+98", flag: "🇮🇷" },
    { code: "IE", name: "Ирландия", dialCode: "+353", flag: "🇮🇪" },
    { code: "IS", name: "Исландия", dialCode: "+354", flag: "🇮🇸" },
    { code: "ES", name: "Испания", dialCode: "+34", flag: "🇪🇸" },
    { code: "IT", name: "Италия", dialCode: "+39", flag: "🇮🇹" },
    { code: "YE", name: "Йемен", dialCode: "+967", flag: "🇾🇪" },
    { code: "CV", name: "Кабо-Верде", dialCode: "+238", flag: "🇨🇻" },
    { code: "KZ", name: "Казахстан", dialCode: "+7", flag: "🇰🇿" },
    { code: "KY", name: "Каймановы острова", dialCode: "+1345", flag: "🇰🇾" },
    { code: "KH", name: "Камбоджа", dialCode: "+855", flag: "🇰🇭" },
    { code: "CM", name: "Камерун", dialCode: "+237", flag: "🇨🇲" },
    { code: "CA", name: "Канада", dialCode: "+1", flag: "🇨🇦" },
    { code: "QA", name: "Катар", dialCode: "+974", flag: "🇶🇦" },
    { code: "KE", name: "Кения", dialCode: "+254", flag: "🇰🇪" },
    { code: "CY", name: "Кипр", dialCode: "+357", flag: "🇨🇾" },
    { code: "KG", name: "Киргизия", dialCode: "+996", flag: "🇰🇬" },
    { code: "KI", name: "Кирибати", dialCode: "+686", flag: "🇰🇮" },
    { code: "CN", name: "Китай", dialCode: "+86", flag: "🇨🇳" },
    { code: "CO", name: "Колумбия", dialCode: "+57", flag: "🇨🇴" },
    { code: "KM", name: "Коморы", dialCode: "+269", flag: "🇰🇲" },
    { code: "CD", name: "Конго (ДРК)", dialCode: "+243", flag: "🇨🇩" },
    { code: "CG", name: "Конго (Республика)", dialCode: "+242", flag: "🇨🇬" },
    { code: "XK", name: "Косово", dialCode: "+383", flag: "🇽🇰" },
    { code: "CR", name: "Коста-Рика", dialCode: "+506", flag: "🇨🇷" },
    { code: "CI", name: "Кот-д'Ивуар", dialCode: "+225", flag: "🇨🇮" },
    { code: "CU", name: "Куба", dialCode: "+53", flag: "🇨🇺" },
    { code: "KW", name: "Кувейт", dialCode: "+965", flag: "🇰🇼" },
    { code: "CW", name: "Кюрасао", dialCode: "+599", flag: "🇨🇼" },
    { code: "LA", name: "Лаос", dialCode: "+856", flag: "🇱🇦" },
    { code: "LV", name: "Латвия", dialCode: "+371", flag: "🇱🇻" },
    { code: "LS", name: "Лесото", dialCode: "+266", flag: "🇱🇸" },
    { code: "LR", name: "Либерия", dialCode: "+231", flag: "🇱🇷" },
    { code: "LB", name: "Ливан", dialCode: "+961", flag: "🇱🇧" },
    { code: "LY", name: "Ливия", dialCode: "+218", flag: "🇱🇾" },
    { code: "LT", name: "Литва", dialCode: "+370", flag: "🇱🇹" },
    { code: "LI", name: "Лихтенштейн", dialCode: "+423", flag: "🇱🇮" },
    { code: "LU", name: "Люксембург", dialCode: "+352", flag: "🇱🇺" },
    { code: "MU", name: "Маврикий", dialCode: "+230", flag: "🇲🇺" },
    { code: "MR", name: "Мавритания", dialCode: "+222", flag: "🇲🇷" },
    { code: "MG", name: "Мадагаскар", dialCode: "+261", flag: "🇲🇬" },
    { code: "MO", name: "Макао", dialCode: "+853", flag: "🇲🇴" },
    { code: "MW", name: "Малави", dialCode: "+265", flag: "🇲🇼" },
    { code: "MY", name: "Малайзия", dialCode: "+60", flag: "🇲🇾" },
    { code: "ML", name: "Мали", dialCode: "+223", flag: "🇲🇱" },
    { code: "MV", name: "Мальдивы", dialCode: "+960", flag: "🇲🇻" },
    { code: "MT", name: "Мальта", dialCode: "+356", flag: "🇲🇹" },
    { code: "MA", name: "Марокко", dialCode: "+212", flag: "🇲🇦" },
    { code: "MQ", name: "Мартиника", dialCode: "+596", flag: "🇲🇶" },
    { code: "MH", name: "Маршалловы Острова", dialCode: "+692", flag: "🇲🇭" },
    { code: "MX", name: "Мексика", dialCode: "+52", flag: "🇲🇽" },
    { code: "FM", name: "Микронезия", dialCode: "+691", flag: "🇫🇲" },
    { code: "MZ", name: "Мозамбик", dialCode: "+258", flag: "🇲🇿" },
    { code: "MD", name: "Молдавия", dialCode: "+373", flag: "🇲🇩" },
    { code: "MC", name: "Монако", dialCode: "+377", flag: "🇲🇨" },
    { code: "MN", name: "Монголия", dialCode: "+976", flag: "🇲🇳" },
    { code: "MS", name: "Монтсеррат", dialCode: "+1664", flag: "🇲🇸" },
    { code: "MM", name: "Мьянма", dialCode: "+95", flag: "🇲🇲" },
    { code: "NA", name: "Намибия", dialCode: "+264", flag: "🇳🇦" },
    { code: "NR", name: "Науру", dialCode: "+674", flag: "🇳🇷" },
    { code: "NP", name: "Непал", dialCode: "+977", flag: "🇳🇵" },
    { code: "NE", name: "Нигер", dialCode: "+227", flag: "🇳🇪" },
    { code: "NG", name: "Нигерия", dialCode: "+234", flag: "🇳🇬" },
    { code: "NL", name: "Нидерланды", dialCode: "+31", flag: "🇳🇱" },
    { code: "NI", name: "Никарагуа", dialCode: "+505", flag: "🇳🇮" },
    { code: "NU", name: "Ниуэ", dialCode: "+683", flag: "🇳🇺" },
    { code: "NZ", name: "Новая Зеландия", dialCode: "+64", flag: "🇳🇿" },
    { code: "NC", name: "Новая Каледония", dialCode: "+687", flag: "🇳🇨" },
    { code: "NO", name: "Норвегия", dialCode: "+47", flag: "🇳🇴" },
    { code: "AE", name: "ОАЭ", dialCode: "+971", flag: "🇦🇪" },
    { code: "OM", name: "Оман", dialCode: "+968", flag: "🇴🇲" },
    { code: "NF", name: "Остров Норфолк", dialCode: "+672", flag: "🇳🇫" },
    { code: "SH", name: "Остров Святой Елены", dialCode: "+247", flag: "🇸🇭" },
    { code: "SH", name: "Остров Святой Елены", dialCode: "+290", flag: "🇸🇭" },
    { code: "CK", name: "Острова Кука", dialCode: "+682", flag: "🇨🇰" },
    { code: "PK", name: "Пакистан", dialCode: "+92", flag: "🇵🇰" },
    { code: "PW", name: "Палау", dialCode: "+680", flag: "🇵🇼" },
    { code: "PS", name: "Палестина", dialCode: "+970", flag: "🇵🇸" },
    { code: "PA", name: "Панама", dialCode: "+507", flag: "🇵🇦" },
    { code: "PG", name: "Папуа — Новая Гвинея", dialCode: "+675", flag: "🇵🇬" },
    { code: "PY", name: "Парагвай", dialCode: "+595", flag: "🇵🇾" },
    { code: "PE", name: "Перу", dialCode: "+51", flag: "🇵🇪" },
    { code: "PL", name: "Польша", dialCode: "+48", flag: "🇵🇱" },
    { code: "PT", name: "Португалия", dialCode: "+351", flag: "🇵🇹" },
    { code: "PR", name: "Пуэрто-Рико", dialCode: "+1787", flag: "🇵🇷" },
    { code: "PR", name: "Пуэрто-Рико", dialCode: "+1939", flag: "🇵🇷" },
    { code: "RE", name: "Реюньон", dialCode: "+262", flag: "🇷🇪" },
    { code: "RW", name: "Руанда", dialCode: "+250", flag: "🇷🇼" },
    { code: "RO", name: "Румыния", dialCode: "+40", flag: "🇷🇴" },
    { code: "SV", name: "Сальвадор", dialCode: "+503", flag: "🇸🇻" },
    { code: "WS", name: "Самоа", dialCode: "+685", flag: "🇼🇸" },
    { code: "SM", name: "Сан-Марино", dialCode: "+378", flag: "🇸🇲" },
    { code: "ST", name: "Сан-Томе и Принсипи", dialCode: "+239", flag: "🇸🇹" },
    { code: "SA", name: "Саудовская Аравия", dialCode: "+966", flag: "🇸🇦" },
    { code: "MK", name: "Северная Македония", dialCode: "+389", flag: "🇲🇰" },
    { code: "MP", name: "Северные Марианские о-ва", dialCode: "+1670", flag: "🇲🇵" },
    { code: "SC", name: "Сейшельские Острова", dialCode: "+248", flag: "🇸🇨" },
    { code: "BL", name: "Сен-Бартелеми", dialCode: "+590", flag: "🇧🇱" },
    { code: "MF", name: "Сен-Мартен", dialCode: "+590", flag: "🇲🇫" },
    { code: "PM", name: "Сен-Пьер и Микелон", dialCode: "+508", flag: "🇵🇲" },
    { code: "SN", name: "Сенегал", dialCode: "+221", flag: "🇸🇳" },
    { code: "VC", name: "Сент-Винсент и Гренадины", dialCode: "+1784", flag: "🇻🇨" },
    { code: "KN", name: "Сент-Китс и Невис", dialCode: "+1869", flag: "🇰🇳" },
    { code: "LC", name: "Сент-Люсия", dialCode: "+1758", flag: "🇱🇨" },
    { code: "RS", name: "Сербия", dialCode: "+381", flag: "🇷🇸" },
    { code: "SG", name: "Сингапур", dialCode: "+65", flag: "🇸🇬" },
    { code: "SX", name: "Синт-Мартен", dialCode: "+1721", flag: "🇸🇽" },
    { code: "SY", name: "Сирия", dialCode: "+963", flag: "🇸🇾" },
    { code: "SK", name: "Словакия", dialCode: "+421", flag: "🇸🇰" },
    { code: "SI", name: "Словения", dialCode: "+386", flag: "🇸🇮" },
    { code: "SB", name: "Соломоновы Острова", dialCode: "+677", flag: "🇸🇧" },
    { code: "SO", name: "Сомали", dialCode: "+252", flag: "🇸🇴" },
    { code: "SD", name: "Судан", dialCode: "+249", flag: "🇸🇩" },
    { code: "SR", name: "Суринам", dialCode: "+597", flag: "🇸🇷" },
    { code: "US", name: "США", dialCode: "+1", flag: "🇺🇸" },
    { code: "SL", name: "Сьерра-Леоне", dialCode: "+232", flag: "🇸🇱" },
    { code: "TJ", name: "Таджикистан", dialCode: "+992", flag: "🇹🇯" },
    { code: "TH", name: "Таиланд", dialCode: "+66", flag: "🇹🇭" },
    { code: "TW", name: "Тайвань", dialCode: "+886", flag: "🇹🇼" },
    { code: "TZ", name: "Танзания", dialCode: "+255", flag: "🇹🇿" },
    { code: "TC", name: "Тёркс и Кайкос", dialCode: "+1649", flag: "🇹🇨" },
    { code: "TG", name: "Того", dialCode: "+228", flag: "🇹🇬" },
    { code: "TK", name: "Токелау", dialCode: "+690", flag: "🇹🇰" },
    { code: "TO", name: "Тонга", dialCode: "+676", flag: "🇹🇴" },
    { code: "TT", name: "Тринидад и Тобаго", dialCode: "+1868", flag: "🇹🇹" },
    { code: "TV", name: "Тувалу", dialCode: "+688", flag: "🇹🇻" },
    { code: "TN", name: "Тунис", dialCode: "+216", flag: "🇹🇳" },
    { code: "TM", name: "Туркменистан", dialCode: "+993", flag: "🇹🇲" },
    { code: "TR", name: "Турция", dialCode: "+90", flag: "🇹🇷" },
    { code: "UG", name: "Уганда", dialCode: "+256", flag: "🇺🇬" },
    { code: "UZ", name: "Узбекистан", dialCode: "+998", flag: "🇺🇿" },
    { code: "UA", name: "Украина", dialCode: "+380", flag: "🇺🇦" },
    { code: "WF", name: "Уоллис и Футуна", dialCode: "+681", flag: "🇼🇫" },
    { code: "UY", name: "Уругвай", dialCode: "+598", flag: "🇺🇾" },
    { code: "FO", name: "Фарерские острова", dialCode: "+298", flag: "🇫🇴" },
    { code: "PH", name: "Филиппины", dialCode: "+63", flag: "🇵🇭" },
    { code: "FI", name: "Финляндия", dialCode: "+358", flag: "🇫🇮" },
    { code: "FK", name: "Фолклендские острова", dialCode: "+500", flag: "🇫🇰" },
    { code: "FR", name: "Франция", dialCode: "+33", flag: "🇫🇷" },
    { code: "PF", name: "Французская Полинезия", dialCode: "+689", flag: "🇵🇫" },
    { code: "HR", name: "Хорватия", dialCode: "+385", flag: "🇭🇷" },
    { code: "CF", name: "ЦАР", dialCode: "+236", flag: "🇨🇫" },
    { code: "TD", name: "Чад", dialCode: "+235", flag: "🇹🇩" },
    { code: "ME", name: "Черногория", dialCode: "+382", flag: "🇲🇪" },
    { code: "CZ", name: "Чехия", dialCode: "+420", flag: "🇨🇿" },
    { code: "CL", name: "Чили", dialCode: "+56", flag: "🇨🇱" },
    { code: "CH", name: "Швейцария", dialCode: "+41", flag: "🇨🇭" },
    { code: "SE", name: "Швеция", dialCode: "+46", flag: "🇸🇪" },
    { code: "LK", name: "Шри-Ланка", dialCode: "+94", flag: "🇱🇰" },
    { code: "EC", name: "Эквадор", dialCode: "+593", flag: "🇪🇨" },
    { code: "GQ", name: "Экваториальная Гвинея", dialCode: "+240", flag: "🇬🇶" },
    { code: "ER", name: "Эритрея", dialCode: "+291", flag: "🇪🇷" },
    { code: "SZ", name: "Эсватини", dialCode: "+268", flag: "🇸🇿" },
    { code: "EE", name: "Эстония", dialCode: "+372", flag: "🇪🇪" },
    { code: "ET", name: "Эфиопия", dialCode: "+251", flag: "🇪🇹" },
    { code: "ZA", name: "ЮАР", dialCode: "+27", flag: "🇿🇦" },
    { code: "KR", name: "Южная Корея", dialCode: "+82", flag: "🇰🇷" },
    { code: "SS", name: "Южный Судан", dialCode: "+211", flag: "🇸🇸" },
    { code: "JM", name: "Ямайка", dialCode: "+1876", flag: "🇯🇲" },
    { code: "JP", name: "Япония", dialCode: "+81", flag: "🇯🇵" },
];

export const DEFAULT_COUNTRY = COUNTRIES[0];

/** Find the best matching country by dial code prefix. */
export function findCountryByDialCode(dialCode: string): CountryEntry | undefined {
    const clean = dialCode.startsWith("+") ? dialCode : `+${dialCode}`;
    // Prefer exact match, then longest prefix match
    return (
        COUNTRIES.find((c) => c.dialCode === clean) ??
        COUNTRIES.filter((c) => clean.startsWith(c.dialCode))
            .sort((a, b) => b.dialCode.length - a.dialCode.length)[0]
    );
}
