/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UtmCodeRouteImport } from './routes/utm/$code'
import { Route as GoManagerRouteImport } from './routes/go.manager'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AuthWelcomeRouteImport } from './routes/_auth.welcome'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPromptsRouteImport } from './routes/_app.prompts'
import { Route as AppMyChatRouteImport } from './routes/_app.my-chat'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatsRouteImport } from './routes/_app.chats'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppBalanceRouteImport } from './routes/_app.balance'
import { Route as AppAppealsRouteImport } from './routes/_app.appeals'
import { Route as AppAccessRouteImport } from './routes/_app.access'
import { Route as AdminUtmIndexRouteImport } from './routes/admin/utm/index'
import { Route as AdminUtmNewRouteImport } from './routes/admin/utm/new'
import { Route as AppChatChatIdRouteImport } from './routes/_app.chat.$chatId'
import { Route as AuthAuthOauthCallbackRouteImport } from './routes/_auth.auth.oauth.callback'

const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UtmCodeRoute = UtmCodeRouteImport.update({
  id: '/utm/$code',
  path: '/utm/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GoManagerRoute = GoManagerRouteImport.update({
  id: '/go/manager',
  path: '/go/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthWelcomeRoute = AuthWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptsRoute = AppPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppMyChatRoute = AppMyChatRouteImport.update({
  id: '/my-chat',
  path: '/my-chat',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBalanceRoute = AppBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AppRoute,
} as any)
const AppAppealsRoute = AppAppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AdminUtmIndexRoute = AdminUtmIndexRouteImport.update({
  id: '/utm/',
  path: '/utm/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUtmNewRoute = AdminUtmNewRouteImport.update({
  id: '/utm/new',
  path: '/utm/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppChatChatIdRoute = AppChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AppChatRoute,
} as any)
const AuthAuthOauthCallbackRoute = AuthAuthOauthCallbackRouteImport.update({
  id: '/auth/oauth/callback',
  path: '/auth/oauth/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/guide': typeof GuideRoute
  '/access': typeof AppAccessRoute
  '/appeals': typeof AppAppealsRoute
  '/balance': typeof AppBalanceRoute
  '/chat': typeof AppChatRouteWithChildren
  '/chats': typeof AppChatsRoute
  '/dashboard': typeof AppDashboardRoute
  '/leads': typeof AppLeadsRoute
  '/my-chat': typeof AppMyChatRoute
  '/prompts': typeof AppPromptsRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/welcome': typeof AuthWelcomeRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/login': typeof AdminLoginRoute
  '/go/manager': typeof GoManagerRoute
  '/utm/$code': typeof UtmCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/admin/utm/new': typeof AdminUtmNewRoute
  '/admin/utm/': typeof AdminUtmIndexRoute
  '/auth/oauth/callback': typeof AuthAuthOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/guide': typeof GuideRoute
  '/access': typeof AppAccessRoute
  '/appeals': typeof AppAppealsRoute
  '/balance': typeof AppBalanceRoute
  '/chat': typeof AppChatRouteWithChildren
  '/chats': typeof AppChatsRoute
  '/dashboard': typeof AppDashboardRoute
  '/leads': typeof AppLeadsRoute
  '/my-chat': typeof AppMyChatRoute
  '/prompts': typeof AppPromptsRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/welcome': typeof AuthWelcomeRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/login': typeof AdminLoginRoute
  '/go/manager': typeof GoManagerRoute
  '/utm/$code': typeof UtmCodeRoute
  '/admin': typeof AdminIndexRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/admin/utm/new': typeof AdminUtmNewRoute
  '/admin/utm': typeof AdminUtmIndexRoute
  '/auth/oauth/callback': typeof AuthAuthOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/guide': typeof GuideRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/appeals': typeof AppAppealsRoute
  '/_app/balance': typeof AppBalanceRoute
  '/_app/chat': typeof AppChatRouteWithChildren
  '/_app/chats': typeof AppChatsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/my-chat': typeof AppMyChatRoute
  '/_app/prompts': typeof AppPromptsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/welcome': typeof AuthWelcomeRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/login': typeof AdminLoginRoute
  '/go/manager': typeof GoManagerRoute
  '/utm/$code': typeof UtmCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/chat/$chatId': typeof AppChatChatIdRoute
  '/admin/utm/new': typeof AdminUtmNewRoute
  '/admin/utm/': typeof AdminUtmIndexRoute
  '/_auth/auth/oauth/callback': typeof AuthAuthOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$'
    | '/guide'
    | '/access'
    | '/appeals'
    | '/balance'
    | '/chat'
    | '/chats'
    | '/dashboard'
    | '/leads'
    | '/my-chat'
    | '/prompts'
    | '/settings'
    | '/login'
    | '/register'
    | '/welcome'
    | '/admin/clients'
    | '/admin/login'
    | '/go/manager'
    | '/utm/$code'
    | '/admin/'
    | '/chat/$chatId'
    | '/admin/utm/new'
    | '/admin/utm/'
    | '/auth/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/guide'
    | '/access'
    | '/appeals'
    | '/balance'
    | '/chat'
    | '/chats'
    | '/dashboard'
    | '/leads'
    | '/my-chat'
    | '/prompts'
    | '/settings'
    | '/login'
    | '/register'
    | '/welcome'
    | '/admin/clients'
    | '/admin/login'
    | '/go/manager'
    | '/utm/$code'
    | '/admin'
    | '/chat/$chatId'
    | '/admin/utm/new'
    | '/admin/utm'
    | '/auth/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$'
    | '/_app'
    | '/_auth'
    | '/guide'
    | '/_app/access'
    | '/_app/appeals'
    | '/_app/balance'
    | '/_app/chat'
    | '/_app/chats'
    | '/_app/dashboard'
    | '/_app/leads'
    | '/_app/my-chat'
    | '/_app/prompts'
    | '/_app/settings'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/welcome'
    | '/admin/clients'
    | '/admin/login'
    | '/go/manager'
    | '/utm/$code'
    | '/admin/'
    | '/_app/chat/$chatId'
    | '/admin/utm/new'
    | '/admin/utm/'
    | '/_auth/auth/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  GuideRoute: typeof GuideRoute
  GoManagerRoute: typeof GoManagerRoute
  UtmCodeRoute: typeof UtmCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/utm/$code': {
      id: '/utm/$code'
      path: '/utm/$code'
      fullPath: '/utm/$code'
      preLoaderRoute: typeof UtmCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/manager': {
      id: '/go/manager'
      path: '/go/manager'
      fullPath: '/go/manager'
      preLoaderRoute: typeof GoManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/welcome': {
      id: '/_auth/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthWelcomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prompts': {
      id: '/_app/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AppPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-chat': {
      id: '/_app/my-chat'
      path: '/my-chat'
      fullPath: '/my-chat'
      preLoaderRoute: typeof AppMyChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats': {
      id: '/_app/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/balance': {
      id: '/_app/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof AppBalanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appeals': {
      id: '/_app/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AppAppealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/utm/': {
      id: '/admin/utm/'
      path: '/utm'
      fullPath: '/admin/utm/'
      preLoaderRoute: typeof AdminUtmIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/utm/new': {
      id: '/admin/utm/new'
      path: '/utm/new'
      fullPath: '/admin/utm/new'
      preLoaderRoute: typeof AdminUtmNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/chat/$chatId': {
      id: '/_app/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AppChatChatIdRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_auth/auth/oauth/callback': {
      id: '/_auth/auth/oauth/callback'
      path: '/auth/oauth/callback'
      fullPath: '/auth/oauth/callback'
      preLoaderRoute: typeof AuthAuthOauthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUtmNewRoute: typeof AdminUtmNewRoute
  AdminUtmIndexRoute: typeof AdminUtmIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUtmNewRoute: AdminUtmNewRoute,
  AdminUtmIndexRoute: AdminUtmIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppChatRouteChildren {
  AppChatChatIdRoute: typeof AppChatChatIdRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatChatIdRoute: AppChatChatIdRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppRouteChildren {
  AppAccessRoute: typeof AppAccessRoute
  AppAppealsRoute: typeof AppAppealsRoute
  AppBalanceRoute: typeof AppBalanceRoute
  AppChatRoute: typeof AppChatRouteWithChildren
  AppChatsRoute: typeof AppChatsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMyChatRoute: typeof AppMyChatRoute
  AppPromptsRoute: typeof AppPromptsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessRoute: AppAccessRoute,
  AppAppealsRoute: AppAppealsRoute,
  AppBalanceRoute: AppBalanceRoute,
  AppChatRoute: AppChatRouteWithChildren,
  AppChatsRoute: AppChatsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMyChatRoute: AppMyChatRoute,
  AppPromptsRoute: AppPromptsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthWelcomeRoute: typeof AuthWelcomeRoute
  AuthAuthOauthCallbackRoute: typeof AuthAuthOauthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthWelcomeRoute: AuthWelcomeRoute,
  AuthAuthOauthCallbackRoute: AuthAuthOauthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  GuideRoute: GuideRoute,
  GoManagerRoute: GoManagerRoute,
  UtmCodeRoute: UtmCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
